import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1440, height: 900 } });
const fouten = []; p.on('pageerror', e => fouten.push(e.message));
await p.goto('http://localhost:8899/mockups/branche-defensie-v2.html');
await p.waitForTimeout(900);
console.log('kaarten:', await p.locator('.kop3 .kaart').count());
console.log('teller:', (await p.textContent('[data-spoor-tel]'))?.trim());
await p.screenshot({ path: process.argv[2] + '/hero3.png' });
await p.click('[data-spoor-verder]');
await p.waitForTimeout(700);
console.log('na schuiven:', (await p.textContent('[data-spoor-tel]'))?.trim());
console.log(fouten.length ? 'JS-FOUTEN: ' + fouten.join(' | ') : 'geen javascriptfouten');
await b.close();
