import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1440, height: 950 } });
const fouten = [], kapot = [];
p.on('pageerror', e => fouten.push(e.message));
p.on('response', r => { if (r.status() >= 400) kapot.push(r.url().split('/').pop()); });
await p.goto('http://localhost:8899/mockups/branche-defensie-v3.html');
await p.waitForTimeout(1000);
console.log('secties:', await p.locator('body > section').count(), '| plusjes:', await p.locator('.pluspunten span').count(), '| details:', await p.locator('.merk2').count());
await p.locator('.constructie').scrollIntoViewIfNeeded(); await p.waitForTimeout(500);
await p.screenshot({ path: process.argv[2] + '/constructie.png' });
console.log(kapot.length ? 'ONTBREEKT: ' + [...new Set(kapot)].join(', ') : 'geen 404s');
console.log(fouten.length ? 'JS-FOUTEN: ' + fouten.join(' | ') : 'geen javascriptfouten');
await b.close();
