import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1440, height: 800 } });
const fouten = []; p.on('pageerror', e => fouten.push(e.message));
await p.goto('http://localhost:8899/mockups/branche-defensie-v3.html?vervoeren=F16%20vleugel');
await p.waitForTimeout(800);
const box = await p.locator('.ontvangst').boundingBox();
console.log('hoogte strook:', box ? Math.round(box.height) + 'px' : 'ONTBREEKT', '(was 257)');
console.log('wit vlak weg:', await p.locator('.ontvangst .uitleg').count() === 0);
await p.screenshot({ path: process.argv[2] + '/ontv-nieuw.png' });
console.log(fouten.length ? 'JS-FOUTEN: ' + fouten.join(' | ') : 'geen javascriptfouten');
await b.close();
