import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1440, height: 950 } });
const fouten = []; p.on('pageerror', e => fouten.push(e.message));
await p.goto('http://localhost:8899/mockups/branche-defensie-v3.html');
await p.waitForTimeout(900);
const bal = await p.locator('.pluspunten').boundingBox();
console.log('hoogte plusjesbalk:', bal ? Math.round(bal.height) + 'px' : '?');
console.log('foto in eisenblok:', await p.locator('.eisen2 .fotokant img').count(), '| sommen:', await p.locator('.eisen2 .som').count());
await p.locator('.eisen2').scrollIntoViewIfNeeded(); await p.waitForTimeout(500);
await p.screenshot({ path: process.argv[2] + '/eisen-foto.png' });
console.log(fouten.length ? 'JS-FOUTEN: ' + fouten.join(' | ') : 'geen javascriptfouten');
await b.close();
