import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1440, height: 950 } });
const fouten = []; p.on('pageerror', e => fouten.push(e.message));
await p.goto('http://localhost:8899/mockups/branche-defensie-v2.html');
await p.waitForTimeout(700);
console.log('opdrachten open:', await p.locator('.opdracht').count());
console.log('nog details-elementen in werk:', await p.locator('.werk2 details').count());
const el = p.locator('.opdracht').first();
await el.scrollIntoViewIfNeeded(); await p.waitForTimeout(400);
await p.screenshot({ path: process.argv[2] + '/werk-nieuw.png' });
await p.locator('.band').first().scrollIntoViewIfNeeded(); await p.waitForTimeout(400);
await p.screenshot({ path: process.argv[2] + '/band-ruit.png' });
console.log(fouten.length ? 'JS-FOUTEN: ' + fouten.join(' | ') : 'geen javascriptfouten');
await b.close();
