import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1440, height: 950 } });
const fouten = [], kapot = [];
p.on('pageerror', e => fouten.push(e.message));
p.on('response', r => { if (r.status() >= 400) kapot.push(r.url().split('/').pop()); });
await p.goto('http://localhost:8899/mockups/branche-defensie-v3.html');
await p.waitForTimeout(900);
console.log('secties:', await p.locator('body > section').count(), '| modellen:', await p.locator('.kisten .kist').count(), '| strook:', await p.locator('.klanten .plek').count());
console.log('bijschrift-bronnen:', await p.locator('.bron').count(), '| streep weg:', !(await p.locator('.eisen2 figcaption').evaluate(e => getComputedStyle(e).borderLeftWidth !== '0px').catch(() => false)));
await p.locator('.klanten').scrollIntoViewIfNeeded(); await p.waitForTimeout(600);
await p.screenshot({ path: process.argv[2] + '/strook.png' });
console.log(kapot.length ? 'ONTBREEKT: ' + [...new Set(kapot)].join(', ') : 'geen 404s');
console.log(fouten.length ? 'JS-FOUTEN: ' + fouten.join(' | ') : 'geen javascriptfouten');
await b.close();
